### ISSUE TITLE
Inconsistent output

### ISSUE THREAD

**Issue by foxfirecodes** [ArsenArsen/prime_machine#1]
```
...
999953
999961
999979
999983
999959
```
```
...
999953
999961
999959
999979
999983
```
```
...
999953
999959
999979
999961
999983
```

As you can see, the output is highly inconsistent. Fix yer crap, Arsen ;P

(on a side note, this is really awesome, I can calculate 1,000,000 prime numbers in ~0.2s, and a quick `sort -n` fixes the output)

**EDIT:** Before you yell at me saying something about the nature of this being multi-threaded, I know, but *still*, it would be nice if the output was actually consistent.

**Comment by ArsenArsen** [comment]
*Technically* it is not sorted, and not inconsistent. And yes, this is due to threading. I'll write something up to queue and print the numbers in order
